import enum

__all__: tuple[str, ...] = ("Languages",)


class Languages(enum.Enum):
    Afrikaans = "af"
    Albanian = "sq"
    Amharic = "am"
    Arabic = "ar"
    Armenian = "hy"
    Azerbaijani = "az"
    Basque = "eu"
    Belarusian = "be"
    Bengali = "bn"
    Bosnian = "bs"
    Bulgarian = "bg"
    Catalan = "ca"
    Cebuano = "ceb"
    Chichewa = "ny"
    Chinese_Simplified = "zh-CN"
    Chinese_Traditional = "zh-TW"
    Corsican = "co"
    Croatian = "hr"
    Czech = "cs"
    Danish = "da"
    Dutch = "nl"
    English = "en"
    Esperanto = "eo"
    Estonian = "et"
    Filipino = "tl"
    Finnish = "fi"
    French = "fr"
    Frisian = "fy"
    Galician = "gl"
    Georgian = "ka"
    German = "de"
    Greek = "el"
    Gujarati = "gu"
    Haitian_Creole = "ht"
    Hausa = "ha"
    Hawaiian = "haw"
    Hebrew = "iw"
    Hindi = "hi"
    Hmong = "hmn"
    Hungarian = "hu"
    Icelandic = "is"
    Igbo = "ig"
    Indonesian = "id"
    Irish = "ga"
    Italian = "it"
    Japanese = "ja"
    Javanese = "jw"
    Kannada = "kn"
    Kazakh = "kk"
    Khmer = "km"
    Korean = "ko"
    Kurdish = "ku"
    Kyrgyz = "ky"
    Lao = "lo"
    Latin = "la"
    Latvian = "lv"
    Lithuanian = "lt"
    Luxembourgish = "lb"
    Macedonian = "mk"
    Malagasy = "mg"
    Malay = "ms"
    Malayalam = "ml"
    Maltese = "mt"
    Maori = "mi"
    Marathi = "mr"
    Mongolian = "mn"
    Myanmar_Burmese = "my"
    Nepali = "ne"
    Norwegian = "no"
    Pashto = "ps"
    Persian = "fa"
    Polish = "pl"
    Portuguese = "pt"
    Punjabi = "pa"
    Romanian = "ro"
    Russian = "ru"
    Samoan = "sm"
    Scots_Gaelic = "gd"
    Serbian = "sr"
    Sesotho = "st"
    Shona = "sn"
    Sindhi = "sd"
    Sinhala = "si"
    Slovak = "sk"
    Slovenian = "sn"
    Somali = "so"
    Spanish = "es"
    Sundanese = "su"
    Swahili = "sw"
    Swedish = "sv"
    Tajik = "tg"
    Tamil = "ta"
    Tatar = "tt"
    Telegu = "te"
    Thai = "th"
    Turkish = "tr"
    Turkmen = "tk"
    Ukrainian = "uk"
    Urdu = "ur"
    Uyghur = "ug"
    Uzbek = "uz"
    Vietnamese = "vi"
    Welsh = "cy"
    Xhosa = "xh"
    Yiddish = "yi"
    Yoruba = "yo"
    Zulu = "zu"

    @classmethod
    def from_string(cls, string: str) -> str:
        for language in cls:
            if string.lower() in language.value.lower():
                return str(language.name).replace("_", " ")
        return str(cls.English.name)

    @classmethod
    def all_languages(cls) -> list[str]:
        return [str(language.value) for language in cls]

    @classmethod
    def language_names(cls) -> list[str]:
        return [cls.from_string(language) for language in cls.all_languages()]
